### ISSUE TITLE
Flatpak最新版 (2025-02-12 17:41:46 +0000) 無法使用

### ISSUE THREAD

**Issue by fsworld009** [openvanilla/fcitx5-mcbopomofo#170]
在您回報問題之前，建議也可以先參考 Wiki 上的 [常見問題](https://github.com/openvanilla/fcitx5-mcbopomofo/wiki/%E5%B8%B8%E8%A6%8B%E5%95%8F%E9%A1%8C) 與 [使用手冊](https://github.com/openvanilla/fcitx5-mcbopomofo/wiki/%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8A)。

在回報問題前，可以試試看，如果切換到了 fcitx5 的其他輸入法，也會遇到相同的問題，那麼也有可能是 fcitx5 本身的問題。小麥注音是在 fcitx5 框架下的眾多輸入法之一，如果是 fcitx5 的問題，那麼也會影響到包含小麥注音的各種輸入法。您可以前往 [fcitx5 官方](https://github.com/fcitx/fcitx5)回報。

如果是詞庫問題，請在[上游專案](https://github.com/openvanilla/fcitx5-mcbopomofo)回報。

**摘要**
請簡單說明您遇到了什麼問題。這份表格雖然是中文的（我們相信注音輸入法的用戶應該都能看懂中文），但開發團隊可以使用中英文溝通，您也可以使用英文回報問題。

**快速分類**
請問您遇到的是：

- [ ] 當機或應用程式閃退
- [x] 輸入法叫不出來，或無法正確輸出中文
- [ ] 無法切換到特定功能
- [ ] 輸入法效能有問題（執行速度太慢/電腦發燙）
- [ ] UI 顯示不正常
- [ ] 其他

**問題發生步驟**
跟 #161 一樣的問題但這次是 `org.fcitx.Fcitx5.Addon.McBopomofo` 最新版有問題

```
❯ flatpak remote-info --log flathub org.fcitx.Fcitx5.Addon.McBopomofo
   Commit: d09d65021c7a4fc83e9f828a5221545f05dc4eca67986e7eb42c213066aa096d
    Parent: 715ac52648b6899affd28040586fa5bab774bd0e4c338c66bb265d9366023d8e
   Subject: fcitx5-mcbopomofo: Update fcitx5-mcbopomofo to 2.9.0 (de7bb559)
      Date: 2025-02-12 17:41:46 +0000
   History: 

    Commit: 715ac52648b6899affd28040586fa5bab774bd0e4c338c66bb265d9366023d8e
   Subject: fcitx5-mcbopomofo: Update fcitx5-mcbopomofo to 2.9.0 (de7bb559)
      Date: 2025-02-12 17:05:36 +0000

    Commit: 3bb8138353caa582c5a9627a92fdc4035ca29ecd7d4e3a9c729887c563f8cfca
   Subject: Update appstream-compose config (fd8a8b8f)
      Date: 2024-11-10 08:07:43 +0000
```

手動安裝舊版McBopomofo再重新載入fcitx5又正常
```
sudo flatpak update --commit=3bb8138353caa582c5a9627a92fdc4035ca29ecd7d4e3a9c729887c563f8cfca org.fcitx.Fcitx5.Addon.McBopomofo
```

Flatpak fcitx5版本
```
    Commit: db396008ac750377d5ff4a1768f526845827a4d7c9a0ab40d530d6d67caf53cb
    Parent: 98d3a3a2c28393b8806641ffd0d80de0857d4f0414ceee1a30abfae58681ba08
   Subject: Update org.fcitx.Fcitx5 to tag-5.1.12 (#45) (a298914c)
      Date: 2025-01-24 22:16:47 +0000
   History: 
```

**預期正常狀況**
fcitx5和McBopomofo都是最新版的情況下輸入法應該要能正常使用

**螢幕截圖或螢幕錄製**
無

**電腦環境**
請問您在怎樣的環境遇到這個問題？

- fcitx5 小麥注音版本：（請填寫版本）
- 鍵盤樣式：
  - [x] 標準
  - [ ] 倚天
  - [ ] 許氏
  - [ ] 倚天 26 鍵
  - [ ] 漢語拼音
  - [ ] IBM
- Linux 發行版本：Fedora Silverblue
- Linux 發行版本系統版本：Aurora DX (rolling release)
- Linux 桌面環境：KDE Plasma 6.2.5
- 安裝方式：Flatpak
- 在哪個應用程式中打字遇到問題：全部
- 其他特殊設備：無
- 特殊設定：無

**其他**
無
